// <auto-generated />
namespace Supporter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class serif1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(serif1));
        
        string IMigrationMetadata.Id
        {
            get { return "201904110846356_serif1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
